### ISSUE TITLE
Customizing Colormap

### ISSUE THREAD

**Issue by kaniblu** [themantalope/pydendroheatmap#1]
I see that in `pydendroheatmap.py`, you have created several color schemes or color maps but have not provided a way for users to choose one and assumes that `self.RedBlackGreen` is the one users want. Do you plan to provide a way to do so? An interface for specifying any color combination or gradient would be even better.

**Comment by themantalope** [comment]
Hey! 

I haven't had time to mess around with this lately, however if you look at lines 382 and down in pydendroheatmap.py, all I'm doing for the colormap is specifying a cdict and then creating a colormap object using LinearSegmentedColormap from the matplotlib library, so as long as your colormap is a valid colormap from matplotlib you can just set your pydendroheatmap object's colormap variable to that.
