### ISSUE TITLE
Dendrograph backwards

### ISSUE THREAD

**Issue by jondeaton** [themantalope/pydendroheatmap#3]
My dendrograph is backwards on the left side and I don't know how to get it flipped. thanks
![phage_heatmap](https://cloud.githubusercontent.com/assets/15920014/14699748/28b76338-074f-11e6-86b5-c8d8f80f0a78.png)

**Comment by themantalope** [comment]
well that's weird. what version of python and matplotlib are you using?

**Comment by themantalope** [comment]
also, would it be possible for you to post some code so I can see what is going on?

**Comment by themantalope** [comment]
Closing the issue. No feedback regarding the bug.
