### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by hsiaoyi0504** [themantalope/pydendroheatmap#4]
I see pydendroheatmap on PyPI,
but it seems that somethings not work.
I installed package through
`pip3 install pydendroheatmap` 
I imported the pydendroheatmap
`import pydendroheatmap as pdh`
but when I try to use
`heatmap = pdh.DendroHeatMap(heat_map_data=corr)`

Error arises
`
AttributeError                            Traceback (most recent call last)
<ipython-input-10-f98dd1056077> in <module>()
----> 1 heatmap = pdh.DendroHeatMap(heat_map_data=corr)
`

`AttributeError: module 'pydendroheatmap' has no attribute DendroHeatMap`

I checked package use following command:
`dir(pdh)`
found that something must be wrong

`['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']
`

**Comment by themantalope** [comment]
Hi hsiaoyi0504,

I have not tried to use the library with python 3, but I know that it works for python 2.7.x. If you would like to try to figure out what is going wrong during the pip install, please let me know, however right now I don't have the resources to figure out support for python 3 myself.

Have you tried downloading the source directory and running `python setup.py install`?

**Comment by hsiaoyi0504** [comment]
Hi themantalope,

So maybe it supposed to be that this package should not be able to be installed through `pip3`.
But I actually can access that through `pip3`.
I am not familiar with the mechanisms lied behind `PyPI`.
However, I see the documentation [here](https://packaging.python.org/distributing/#classifiers)
And I check the `setup.py` in this repo.
I think the configuration you set didn't specify the package should be used only for Python 2.
Then I guess that the default values were assigned, so this makes the confusion.
I suggest you to upload the package to PyPI again with updated configuration.
Therefore, many users like me will not confuse in the future.

Thank you a lot ! I really respect what you did !

**Comment by themantalope** [comment]
Great, thanks for catching that! I'll make the updates as soon as I have a minute.

**Comment by themantalope** [comment]
Again, if you would like to help in configuring the project to use python 3, just let me know!
