### ISSUE TITLE
Python3.4 fix

### ISSUE THREAD

**Issue by pkMyt1** [themantalope/pydendroheatmap#5]
The module does not function correctly in Python 3.4 because of the print calls.  Changing all print "xx" to print("xx") fixes this.

**Comment by themantalope** [comment]
I'll make this change as well. Thanks for pointing this out!

**Comment by themantalope** [comment]
The changes to the `print` statements have been made. Please let me know if the errors from the `print` statements have been fixed.

**Comment by pkMyt1** [comment]
themantalope, other than a missing () on line 133 it is looking good now.  Thanks for making the changes.

Edit:  I will try a pip install when you get it out as well.

**Comment by themantalope** [comment]
Great, I'll add in that fix as well. Closing this issue.
