### ISSUE TITLE
Left Dendrogram Orientation Bug Python 3

### ISSUE THREAD

**Issue by pkMyt1** [themantalope/pydendroheatmap#6]
The left dendrogram is mirrored in Python 3.4.  I have attached the output from the example file.  

![figure1](https://cloud.githubusercontent.com/assets/8458091/18920972/10c9e778-8571-11e6-83c8-0c685db88399.png)

Changing line 142 in pydendroheatmap.py from
`self.left_dendro_plot = sch.dendrogram(self.left_dendrogram,orientation='right')`
to
    `self.left_dendro_plot = sch.dendrogram(self.left_dendrogram,orientation='left')`

solves this issue.

**Comment by themantalope** [comment]
This must have been from a change in the underlying library. Fixed it on my branch, will upload new changes shortly.

**Comment by themantalope** [comment]
@pkMyt1 could you let me know if this has been fixed for you in the latest version available on github?

**Comment by pkMyt1** [comment]
It is fixed now.

**Comment by themantalope** [comment]
Closing this issue.
