### ISSUE TITLE
Possible label bug

### ISSUE THREAD

**Issue by pkMyt1** [themantalope/pydendroheatmap#7]
This might be me missing something but I think the label order is not correct.  The heatmap rearranges the order of the rows and columns in the array but the labels are still the same as the input list.  I made this change to the example.py;

`col_labels = []
    for idx in col_idxing:
        col_labels.append(ylabel[idx])`

where ylabel is from my array.  I guess you could do something like

`col_label = []
     col_labels = {
    for i in range(50):
        col_label.append('bla'+i)
    for idx in col_idxing:
        col_labels.append(col_label[idx])`

To keep it consistent with your example.  Keep in mind the range function is different in Python3.

**Comment by themantalope** [comment]
The pydendroheatmap object shouldn't be reordering any of the data, you need to do that yourself.

**Comment by themantalope** [comment]
The reason why I don't apply any reindexing to the labels in the example is because they are all the same, however you would need to reindex the row and column labels if you are doing that for your data after clustering.

**Comment by pkMyt1** [comment]
I did re-index mine.  I missed that your code did not do it automatically.

**Comment by themantalope** [comment]
closing this issue.
