### ISSUE TITLE
Reordering error 重排矩阵错误

### ISSUE THREAD

**Issue by yangmqglobe** [themantalope/pydendroheatmap#8]
In example.py line 87,  you may have some trouble to reordering the data matrix which is use to plot the heatmap, you order it twice, once by columns, once by rows which I think they have to order together.
在示例文件（example.py）中第87行，你可能采用了错误的重排绘制热图的矩阵的方法，你重排了两次，一次是按照列重排，一次是按照行重排，但事实上我认为是需要同时进行的。
PS: The Chinese just for sure that you can get my point by my poor English or you can understood it by my great Chinese, so you may ignore it.

**Comment by themantalope** [comment]
还有木有问题？你要列重排和行重排因为在这个例子中 我假设列的数据跟行的数据是independent，但是别的clustering可以用，比如说row-column bi-clustering. 我要写一个简单的例子script.

**Comment by yangmqglobe** [comment]
Sorry, my fault. My partner told me that this may be error, and I used the wrong data to check. But then I saw another project, I found him with the same way to deal with, so I re-check the problem and found no wrong. I am so sorry about that!
很抱歉，这是我的失误。我的小伙伴告诉我这个错误，但是我使用了错误的数据进行检查。到后来我看到了另外的项目使用了同样的方法解决这个问题，所以我又重新检查了一次，发现并没有错！真的非常抱歉！
Thank you for the translation and your code.

**Comment by yangmqglobe** [comment]
Sorry, my fault. My partner told me that this may be error, and I used the wrong data to check. But then I saw another project, I found him with the same way to deal with, so I re-check the problem and found no wrong. I am so sorry about that!
很抱歉，这是我的失误。我的小伙伴告诉我这个错误，但是我使用了错误的数据进行检查。到后来我看到了另外的项目使用了同样的方法解决这个问题，所以我又重新检查了一次，发现并没有错！真的非常抱歉！
Thank you for the translation and your code.

**Comment by themantalope** [comment]
没事！
